//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReturnCode int32

const (
	// Success response, which represents request execution success.
	ReturnCode_SUCCESS ReturnCode = 0
	//
	// Internal, system-level error codes, which generally cannot be resolved by the user, but
	// instead are due to service issues.
	//
	// Generic internal error occurred.
	ReturnCode_INTERNAL_ERROR ReturnCode = 1
	// An internal system could not be contacted due to a period of unavailability.
	ReturnCode_TEMPORARILY_UNAVAILABLE ReturnCode = 2
	// Indicates that an IOException has been internally thrown.
	ReturnCode_IO_ERROR ReturnCode = 3
	// The request is invalid.
	ReturnCode_BAD_REQUEST ReturnCode = 4
	//
	// Common application-level error codes, which were caused by the user input but may be returned
	// by multiple services.
	//
	// Supplied value for a parameter was invalid (e.g., giving a number for a string parameter).
	ReturnCode_INVALID_PARAMETER_VALUE ReturnCode = 1000
	// Indicates that the given API endpoint does not exist.
	ReturnCode_ENDPOINT_NOT_FOUND ReturnCode = 1001
	// Indicates that the given API request was malformed.
	ReturnCode_MALFORMED_REQUEST ReturnCode = 1002
	// If one or more of the inputs to a given RPC are not in a valid state for the action.
	ReturnCode_INVALID_STATE ReturnCode = 1003
	// If a given user/entity doesn't have the required permission(s) to perform an action
	ReturnCode_PERMISSION_DENIED ReturnCode = 1004
	// If a given user/entity is trying to use a feature which has been disabled
	ReturnCode_FEATURE_DISABLED ReturnCode = 1005
	// If customer-provided credentials are not authorized to perform an operation
	ReturnCode_CUSTOMER_UNAUTHORIZED ReturnCode = 1006
	// If the API request is rejected due to throttling
	ReturnCode_REQUEST_LIMIT_EXCEEDED ReturnCode = 1007
	// Operation was performed on a resource that already exists.
	ReturnCode_RESOURCE_ALREADY_EXISTS ReturnCode = 2001
	// Operation was performed on a resource that does not exist.
	ReturnCode_RESOURCE_DOES_NOT_EXIST ReturnCode = 2002
	// DBFS
	ReturnCode_QUOTA_EXCEEDED          ReturnCode = 3001
	ReturnCode_MAX_BLOCK_SIZE_EXCEEDED ReturnCode = 3002
	ReturnCode_MAX_READ_SIZE_EXCEEDED  ReturnCode = 3003
)

var ReturnCode_name = map[int32]string{
	0:    "SUCCESS",
	1:    "INTERNAL_ERROR",
	2:    "TEMPORARILY_UNAVAILABLE",
	3:    "IO_ERROR",
	4:    "BAD_REQUEST",
	1000: "INVALID_PARAMETER_VALUE",
	1001: "ENDPOINT_NOT_FOUND",
	1002: "MALFORMED_REQUEST",
	1003: "INVALID_STATE",
	1004: "PERMISSION_DENIED",
	1005: "FEATURE_DISABLED",
	1006: "CUSTOMER_UNAUTHORIZED",
	1007: "REQUEST_LIMIT_EXCEEDED",
	2001: "RESOURCE_ALREADY_EXISTS",
	2002: "RESOURCE_DOES_NOT_EXIST",
	3001: "QUOTA_EXCEEDED",
	3002: "MAX_BLOCK_SIZE_EXCEEDED",
	3003: "MAX_READ_SIZE_EXCEEDED",
}

var ReturnCode_value = map[string]int32{
	"SUCCESS":                 0,
	"INTERNAL_ERROR":          1,
	"TEMPORARILY_UNAVAILABLE": 2,
	"IO_ERROR":                3,
	"BAD_REQUEST":             4,
	"INVALID_PARAMETER_VALUE": 1000,
	"ENDPOINT_NOT_FOUND":      1001,
	"MALFORMED_REQUEST":       1002,
	"INVALID_STATE":           1003,
	"PERMISSION_DENIED":       1004,
	"FEATURE_DISABLED":        1005,
	"CUSTOMER_UNAUTHORIZED":   1006,
	"REQUEST_LIMIT_EXCEEDED":  1007,
	"RESOURCE_ALREADY_EXISTS": 2001,
	"RESOURCE_DOES_NOT_EXIST": 2002,
	"QUOTA_EXCEEDED":          3001,
	"MAX_BLOCK_SIZE_EXCEEDED": 3002,
	"MAX_READ_SIZE_EXCEEDED":  3003,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}

func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type DataTypeProto int32

const (
	DataTypeProto_DATA_TYPE_UNSPECIFIED DataTypeProto = 0
	DataTypeProto_INT32                 DataTypeProto = 1
	DataTypeProto_INT64                 DataTypeProto = 2
	DataTypeProto_FLOAT32               DataTypeProto = 3
	DataTypeProto_FLOAT64               DataTypeProto = 4
	DataTypeProto_STRING                DataTypeProto = 5
	DataTypeProto_INT32ARRAY            DataTypeProto = 6
	DataTypeProto_INT64ARRAY            DataTypeProto = 7
	DataTypeProto_FlOAT32ARRAY          DataTypeProto = 8
	DataTypeProto_FLOAT64ARRAY          DataTypeProto = 9
	DataTypeProto_STRINGARRAY           DataTypeProto = 10
	DataTypeProto_BYTES                 DataTypeProto = 11
	DataTypeProto_BYTESARRAY            DataTypeProto = 12
)

var DataTypeProto_name = map[int32]string{
	0:  "DATA_TYPE_UNSPECIFIED",
	1:  "INT32",
	2:  "INT64",
	3:  "FLOAT32",
	4:  "FLOAT64",
	5:  "STRING",
	6:  "INT32ARRAY",
	7:  "INT64ARRAY",
	8:  "FlOAT32ARRAY",
	9:  "FLOAT64ARRAY",
	10: "STRINGARRAY",
	11: "BYTES",
	12: "BYTESARRAY",
}

var DataTypeProto_value = map[string]int32{
	"DATA_TYPE_UNSPECIFIED": 0,
	"INT32":                 1,
	"INT64":                 2,
	"FLOAT32":               3,
	"FLOAT64":               4,
	"STRING":                5,
	"INT32ARRAY":            6,
	"INT64ARRAY":            7,
	"FlOAT32ARRAY":          8,
	"FLOAT64ARRAY":          9,
	"STRINGARRAY":           10,
	"BYTES":                 11,
	"BYTESARRAY":            12,
}

func (x DataTypeProto) String() string {
	return proto.EnumName(DataTypeProto_name, int32(x))
}

func (DataTypeProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type ExampleSupportTypeProto int32

const (
	ExampleSupportTypeProto_EXAMPLE_SUPPORT_TYPE_UNSPECIFIED ExampleSupportTypeProto = 0
	ExampleSupportTypeProto_EXAMPLE_STREAM                   ExampleSupportTypeProto = 1
	ExampleSupportTypeProto_EXAMPLE_BATCH                    ExampleSupportTypeProto = 2
	ExampleSupportTypeProto_EXAMPLE_BOTH                     ExampleSupportTypeProto = 3
)

var ExampleSupportTypeProto_name = map[int32]string{
	0: "EXAMPLE_SUPPORT_TYPE_UNSPECIFIED",
	1: "EXAMPLE_STREAM",
	2: "EXAMPLE_BATCH",
	3: "EXAMPLE_BOTH",
}

var ExampleSupportTypeProto_value = map[string]int32{
	"EXAMPLE_SUPPORT_TYPE_UNSPECIFIED": 0,
	"EXAMPLE_STREAM":                   1,
	"EXAMPLE_BATCH":                    2,
	"EXAMPLE_BOTH":                     3,
}

func (x ExampleSupportTypeProto) String() string {
	return proto.EnumName(ExampleSupportTypeProto_name, int32(x))
}

func (ExampleSupportTypeProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

type StateProto int32

const (
	StateProto_STATE_UNSPECIFIED StateProto = 0
	StateProto_INIT              StateProto = 1
	StateProto_STARTING          StateProto = 2
	StateProto_RUNNING           StateProto = 3
	StateProto_FINISHED          StateProto = 4
	StateProto_FAILED            StateProto = 5
)

var StateProto_name = map[int32]string{
	0: "STATE_UNSPECIFIED",
	1: "INIT",
	2: "STARTING",
	3: "RUNNING",
	4: "FINISHED",
	5: "FAILED",
}

var StateProto_value = map[string]int32{
	"STATE_UNSPECIFIED": 0,
	"INIT":              1,
	"STARTING":          2,
	"RUNNING":           3,
	"FINISHED":          4,
	"FAILED":            5,
}

func (x StateProto) String() string {
	return proto.EnumName(StateProto_name, int32(x))
}

func (StateProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

type ExecutionMode int32

const (
	ExecutionMode_EXECUTION_MODE_UNSPECIFIED ExecutionMode = 0
	ExecutionMode_BATCH                      ExecutionMode = 1
	ExecutionMode_STREAM                     ExecutionMode = 2
)

var ExecutionMode_name = map[int32]string{
	0: "EXECUTION_MODE_UNSPECIFIED",
	1: "BATCH",
	2: "STREAM",
}

var ExecutionMode_value = map[string]int32{
	"EXECUTION_MODE_UNSPECIFIED": 0,
	"BATCH":                      1,
	"STREAM":                     2,
}

func (x ExecutionMode) String() string {
	return proto.EnumName(ExecutionMode_name, int32(x))
}

func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

type ModelType int32

const (
	ModelType_NONE_TYPE   ModelType = 0
	ModelType_CHECKPOINT  ModelType = 1
	ModelType_SAVED_MODEL ModelType = 2
	ModelType_H5          ModelType = 3
)

var ModelType_name = map[int32]string{
	0: "NONE_TYPE",
	1: "CHECKPOINT",
	2: "SAVED_MODEL",
	3: "H5",
}

var ModelType_value = map[string]int32{
	"NONE_TYPE":   0,
	"CHECKPOINT":  1,
	"SAVED_MODEL": 2,
	"H5":          3,
}

func (x ModelType) String() string {
	return proto.EnumName(ModelType_name, int32(x))
}

func (ModelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

type ModelVersionStatus int32

const (
	// Request to register a new model version is pending as server performs background tasks.
	ModelVersionStatus_PENDING_REGISTRATION ModelVersionStatus = 0
	// Request to register a new model version has failed.
	ModelVersionStatus_FAILED_REGISTRATION ModelVersionStatus = 1
	// Model version is ready for use.
	ModelVersionStatus_READY ModelVersionStatus = 3
	// Request to delete an existing model version is pending as server performs background tasks.
	ModelVersionStatus_PENDING_DELETION ModelVersionStatus = 4
	// Request to delete an existing model version has failed.
	ModelVersionStatus_FAILED_DELETION ModelVersionStatus = 5
)

var ModelVersionStatus_name = map[int32]string{
	0: "PENDING_REGISTRATION",
	1: "FAILED_REGISTRATION",
	3: "READY",
	4: "PENDING_DELETION",
	5: "FAILED_DELETION",
}

var ModelVersionStatus_value = map[string]int32{
	"PENDING_REGISTRATION": 0,
	"FAILED_REGISTRATION":  1,
	"READY":                3,
	"PENDING_DELETION":     4,
	"FAILED_DELETION":      5,
}

func (x ModelVersionStatus) String() string {
	return proto.EnumName(ModelVersionStatus_name, int32(x))
}

func (ModelVersionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

type ModelVersionStage int32

const (
	ModelVersionStage_GENERATED  ModelVersionStage = 0
	ModelVersionStage_VALIDATED  ModelVersionStage = 1
	ModelVersionStage_DEPLOYED   ModelVersionStage = 2
	ModelVersionStage_DEPRECATED ModelVersionStage = 3
	ModelVersionStage_DELETED    ModelVersionStage = 4
)

var ModelVersionStage_name = map[int32]string{
	0: "GENERATED",
	1: "VALIDATED",
	2: "DEPLOYED",
	3: "DEPRECATED",
	4: "DELETED",
}

var ModelVersionStage_value = map[string]int32{
	"GENERATED":  0,
	"VALIDATED":  1,
	"DEPLOYED":   2,
	"DEPRECATED": 3,
	"DELETED":    4,
}

func (x ModelVersionStage) String() string {
	return proto.EnumName(ModelVersionStage_name, int32(x))
}

func (ModelVersionStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

type MetricTypeProto int32

const (
	MetricTypeProto_DATASET MetricTypeProto = 0
	MetricTypeProto_MODEL   MetricTypeProto = 1
)

var MetricTypeProto_name = map[int32]string{
	0: "DATASET",
	1: "MODEL",
}

var MetricTypeProto_value = map[string]int32{
	"DATASET": 0,
	"MODEL":   1,
}

func (x MetricTypeProto) String() string {
	return proto.EnumName(MetricTypeProto_name, int32(x))
}

func (MetricTypeProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

type SchemaProto struct {
	NameList             []string        `protobuf:"bytes,1,rep,name=name_list,json=nameList,proto3" json:"name_list,omitempty"`
	TypeList             []DataTypeProto `protobuf:"varint,2,rep,packed,name=type_list,json=typeList,proto3,enum=DataTypeProto" json:"type_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SchemaProto) Reset()         { *m = SchemaProto{} }
func (m *SchemaProto) String() string { return proto.CompactTextString(m) }
func (*SchemaProto) ProtoMessage()    {}
func (*SchemaProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SchemaProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemaProto.Unmarshal(m, b)
}
func (m *SchemaProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemaProto.Marshal(b, m, deterministic)
}
func (m *SchemaProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemaProto.Merge(m, src)
}
func (m *SchemaProto) XXX_Size() int {
	return xxx_messageInfo_SchemaProto.Size(m)
}
func (m *SchemaProto) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemaProto.DiscardUnknown(m)
}

var xxx_messageInfo_SchemaProto proto.InternalMessageInfo

func (m *SchemaProto) GetNameList() []string {
	if m != nil {
		return m.NameList
	}
	return nil
}

func (m *SchemaProto) GetTypeList() []DataTypeProto {
	if m != nil {
		return m.TypeList
	}
	return nil
}

type ExampleProto struct {
	Uuid                 int64                   `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Properties           map[string]string       `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SupportType          ExampleSupportTypeProto `protobuf:"varint,4,opt,name=support_type,json=supportType,proto3,enum=ExampleSupportTypeProto" json:"support_type,omitempty"`
	Schema               *SchemaProto            `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	DataType             *wrappers.StringValue   `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	DataFormat           *wrappers.StringValue   `protobuf:"bytes,7,opt,name=data_format,json=dataFormat,proto3" json:"data_format,omitempty"`
	BatchUri             *wrappers.StringValue   `protobuf:"bytes,8,opt,name=batch_uri,json=batchUri,proto3" json:"batch_uri,omitempty"`
	StreamUri            *wrappers.StringValue   `protobuf:"bytes,9,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	Description          *wrappers.StringValue   `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime           *wrappers.Int64Value    `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *wrappers.Int64Value    `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	CatalogName          *wrappers.StringValue   `protobuf:"bytes,13,opt,name=catalog_name,json=catalogName,proto3" json:"catalog_name,omitempty"`
	CatalogType          *wrappers.StringValue   `protobuf:"bytes,14,opt,name=catalog_type,json=catalogType,proto3" json:"catalog_type,omitempty"`
	CatalogDatabase      *wrappers.StringValue   `protobuf:"bytes,15,opt,name=catalog_database,json=catalogDatabase,proto3" json:"catalog_database,omitempty"`
	CatalogConnectionUri *wrappers.StringValue   `protobuf:"bytes,16,opt,name=catalog_connection_uri,json=catalogConnectionUri,proto3" json:"catalog_connection_uri,omitempty"`
	CatalogVersion       *wrappers.StringValue   `protobuf:"bytes,17,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	CatalogTable         *wrappers.StringValue   `protobuf:"bytes,18,opt,name=catalog_table,json=catalogTable,proto3" json:"catalog_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExampleProto) Reset()         { *m = ExampleProto{} }
func (m *ExampleProto) String() string { return proto.CompactTextString(m) }
func (*ExampleProto) ProtoMessage()    {}
func (*ExampleProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *ExampleProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleProto.Unmarshal(m, b)
}
func (m *ExampleProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleProto.Marshal(b, m, deterministic)
}
func (m *ExampleProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleProto.Merge(m, src)
}
func (m *ExampleProto) XXX_Size() int {
	return xxx_messageInfo_ExampleProto.Size(m)
}
func (m *ExampleProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleProto.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleProto proto.InternalMessageInfo

func (m *ExampleProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *ExampleProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExampleProto) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ExampleProto) GetSupportType() ExampleSupportTypeProto {
	if m != nil {
		return m.SupportType
	}
	return ExampleSupportTypeProto_EXAMPLE_SUPPORT_TYPE_UNSPECIFIED
}

func (m *ExampleProto) GetSchema() *SchemaProto {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *ExampleProto) GetDataType() *wrappers.StringValue {
	if m != nil {
		return m.DataType
	}
	return nil
}

func (m *ExampleProto) GetDataFormat() *wrappers.StringValue {
	if m != nil {
		return m.DataFormat
	}
	return nil
}

func (m *ExampleProto) GetBatchUri() *wrappers.StringValue {
	if m != nil {
		return m.BatchUri
	}
	return nil
}

func (m *ExampleProto) GetStreamUri() *wrappers.StringValue {
	if m != nil {
		return m.StreamUri
	}
	return nil
}

func (m *ExampleProto) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ExampleProto) GetCreateTime() *wrappers.Int64Value {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ExampleProto) GetUpdateTime() *wrappers.Int64Value {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *ExampleProto) GetCatalogName() *wrappers.StringValue {
	if m != nil {
		return m.CatalogName
	}
	return nil
}

func (m *ExampleProto) GetCatalogType() *wrappers.StringValue {
	if m != nil {
		return m.CatalogType
	}
	return nil
}

func (m *ExampleProto) GetCatalogDatabase() *wrappers.StringValue {
	if m != nil {
		return m.CatalogDatabase
	}
	return nil
}

func (m *ExampleProto) GetCatalogConnectionUri() *wrappers.StringValue {
	if m != nil {
		return m.CatalogConnectionUri
	}
	return nil
}

func (m *ExampleProto) GetCatalogVersion() *wrappers.StringValue {
	if m != nil {
		return m.CatalogVersion
	}
	return nil
}

func (m *ExampleProto) GetCatalogTable() *wrappers.StringValue {
	if m != nil {
		return m.CatalogTable
	}
	return nil
}

type ModelRelationProto struct {
	Uuid                 int64                `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectId            *wrappers.Int64Value `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ModelRelationProto) Reset()         { *m = ModelRelationProto{} }
func (m *ModelRelationProto) String() string { return proto.CompactTextString(m) }
func (*ModelRelationProto) ProtoMessage()    {}
func (*ModelRelationProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ModelRelationProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelRelationProto.Unmarshal(m, b)
}
func (m *ModelRelationProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelRelationProto.Marshal(b, m, deterministic)
}
func (m *ModelRelationProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelRelationProto.Merge(m, src)
}
func (m *ModelRelationProto) XXX_Size() int {
	return xxx_messageInfo_ModelRelationProto.Size(m)
}
func (m *ModelRelationProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelRelationProto.DiscardUnknown(m)
}

var xxx_messageInfo_ModelRelationProto proto.InternalMessageInfo

func (m *ModelRelationProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *ModelRelationProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelRelationProto) GetProjectId() *wrappers.Int64Value {
	if m != nil {
		return m.ProjectId
	}
	return nil
}

type ModelProto struct {
	Uuid                 int64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectId            *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ModelType            ModelType             `protobuf:"varint,4,opt,name=model_type,json=modelType,proto3,enum=ModelType" json:"model_type,omitempty"`
	ModelDesc            *wrappers.StringValue `protobuf:"bytes,5,opt,name=model_desc,json=modelDesc,proto3" json:"model_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModelProto) Reset()         { *m = ModelProto{} }
func (m *ModelProto) String() string { return proto.CompactTextString(m) }
func (*ModelProto) ProtoMessage()    {}
func (*ModelProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ModelProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelProto.Unmarshal(m, b)
}
func (m *ModelProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelProto.Marshal(b, m, deterministic)
}
func (m *ModelProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelProto.Merge(m, src)
}
func (m *ModelProto) XXX_Size() int {
	return xxx_messageInfo_ModelProto.Size(m)
}
func (m *ModelProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelProto.DiscardUnknown(m)
}

var xxx_messageInfo_ModelProto proto.InternalMessageInfo

func (m *ModelProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *ModelProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModelProto) GetProjectId() *wrappers.Int64Value {
	if m != nil {
		return m.ProjectId
	}
	return nil
}

func (m *ModelProto) GetModelType() ModelType {
	if m != nil {
		return m.ModelType
	}
	return ModelType_NONE_TYPE
}

func (m *ModelProto) GetModelDesc() *wrappers.StringValue {
	if m != nil {
		return m.ModelDesc
	}
	return nil
}

type ModelVersionRelationProto struct {
	Version              *wrappers.StringValue `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ModelId              *wrappers.Int64Value  `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	WorkflowExecutionId  *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=workflow_execution_id,json=workflowExecutionId,proto3" json:"workflow_execution_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModelVersionRelationProto) Reset()         { *m = ModelVersionRelationProto{} }
func (m *ModelVersionRelationProto) String() string { return proto.CompactTextString(m) }
func (*ModelVersionRelationProto) ProtoMessage()    {}
func (*ModelVersionRelationProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ModelVersionRelationProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelVersionRelationProto.Unmarshal(m, b)
}
func (m *ModelVersionRelationProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelVersionRelationProto.Marshal(b, m, deterministic)
}
func (m *ModelVersionRelationProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelVersionRelationProto.Merge(m, src)
}
func (m *ModelVersionRelationProto) XXX_Size() int {
	return xxx_messageInfo_ModelVersionRelationProto.Size(m)
}
func (m *ModelVersionRelationProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelVersionRelationProto.DiscardUnknown(m)
}

var xxx_messageInfo_ModelVersionRelationProto proto.InternalMessageInfo

func (m *ModelVersionRelationProto) GetVersion() *wrappers.StringValue {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ModelVersionRelationProto) GetModelId() *wrappers.Int64Value {
	if m != nil {
		return m.ModelId
	}
	return nil
}

func (m *ModelVersionRelationProto) GetWorkflowExecutionId() *wrappers.Int64Value {
	if m != nil {
		return m.WorkflowExecutionId
	}
	return nil
}

type ModelVersionProto struct {
	Version              *wrappers.StringValue `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ModelId              *wrappers.Int64Value  `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	WorkflowExecutionId  *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=workflow_execution_id,json=workflowExecutionId,proto3" json:"workflow_execution_id,omitempty"`
	ModelPath            *wrappers.StringValue `protobuf:"bytes,4,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	ModelMetric          *wrappers.StringValue `protobuf:"bytes,5,opt,name=model_metric,json=modelMetric,proto3" json:"model_metric,omitempty"`
	ModelFlavor          *wrappers.StringValue `protobuf:"bytes,6,opt,name=model_flavor,json=modelFlavor,proto3" json:"model_flavor,omitempty"`
	VersionDesc          *wrappers.StringValue `protobuf:"bytes,7,opt,name=version_desc,json=versionDesc,proto3" json:"version_desc,omitempty"`
	CurrentStage         ModelVersionStage     `protobuf:"varint,8,opt,name=current_stage,json=currentStage,proto3,enum=ModelVersionStage" json:"current_stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModelVersionProto) Reset()         { *m = ModelVersionProto{} }
func (m *ModelVersionProto) String() string { return proto.CompactTextString(m) }
func (*ModelVersionProto) ProtoMessage()    {}
func (*ModelVersionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *ModelVersionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelVersionProto.Unmarshal(m, b)
}
func (m *ModelVersionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelVersionProto.Marshal(b, m, deterministic)
}
func (m *ModelVersionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelVersionProto.Merge(m, src)
}
func (m *ModelVersionProto) XXX_Size() int {
	return xxx_messageInfo_ModelVersionProto.Size(m)
}
func (m *ModelVersionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelVersionProto.DiscardUnknown(m)
}

var xxx_messageInfo_ModelVersionProto proto.InternalMessageInfo

func (m *ModelVersionProto) GetVersion() *wrappers.StringValue {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *ModelVersionProto) GetModelId() *wrappers.Int64Value {
	if m != nil {
		return m.ModelId
	}
	return nil
}

func (m *ModelVersionProto) GetWorkflowExecutionId() *wrappers.Int64Value {
	if m != nil {
		return m.WorkflowExecutionId
	}
	return nil
}

func (m *ModelVersionProto) GetModelPath() *wrappers.StringValue {
	if m != nil {
		return m.ModelPath
	}
	return nil
}

func (m *ModelVersionProto) GetModelMetric() *wrappers.StringValue {
	if m != nil {
		return m.ModelMetric
	}
	return nil
}

func (m *ModelVersionProto) GetModelFlavor() *wrappers.StringValue {
	if m != nil {
		return m.ModelFlavor
	}
	return nil
}

func (m *ModelVersionProto) GetVersionDesc() *wrappers.StringValue {
	if m != nil {
		return m.VersionDesc
	}
	return nil
}

func (m *ModelVersionProto) GetCurrentStage() ModelVersionStage {
	if m != nil {
		return m.CurrentStage
	}
	return ModelVersionStage_GENERATED
}

type JobProto struct {
	Uuid                 int64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WorkflowExecutionId  *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=workflow_execution_id,json=workflowExecutionId,proto3" json:"workflow_execution_id,omitempty"`
	JobState             StateProto            `protobuf:"varint,4,opt,name=job_state,json=jobState,proto3,enum=StateProto" json:"job_state,omitempty"`
	Properties           map[string]string     `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	JobId                *wrappers.StringValue `protobuf:"bytes,6,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StartTime            *wrappers.Int64Value  `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *wrappers.Int64Value  `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LogUri               *wrappers.StringValue `protobuf:"bytes,9,opt,name=log_uri,json=logUri,proto3" json:"log_uri,omitempty"`
	Signature            *wrappers.StringValue `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *JobProto) Reset()         { *m = JobProto{} }
func (m *JobProto) String() string { return proto.CompactTextString(m) }
func (*JobProto) ProtoMessage()    {}
func (*JobProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *JobProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobProto.Unmarshal(m, b)
}
func (m *JobProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobProto.Marshal(b, m, deterministic)
}
func (m *JobProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobProto.Merge(m, src)
}
func (m *JobProto) XXX_Size() int {
	return xxx_messageInfo_JobProto.Size(m)
}
func (m *JobProto) XXX_DiscardUnknown() {
	xxx_messageInfo_JobProto.DiscardUnknown(m)
}

var xxx_messageInfo_JobProto proto.InternalMessageInfo

func (m *JobProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *JobProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobProto) GetWorkflowExecutionId() *wrappers.Int64Value {
	if m != nil {
		return m.WorkflowExecutionId
	}
	return nil
}

func (m *JobProto) GetJobState() StateProto {
	if m != nil {
		return m.JobState
	}
	return StateProto_STATE_UNSPECIFIED
}

func (m *JobProto) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *JobProto) GetJobId() *wrappers.StringValue {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *JobProto) GetStartTime() *wrappers.Int64Value {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *JobProto) GetEndTime() *wrappers.Int64Value {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *JobProto) GetLogUri() *wrappers.StringValue {
	if m != nil {
		return m.LogUri
	}
	return nil
}

func (m *JobProto) GetSignature() *wrappers.StringValue {
	if m != nil {
		return m.Signature
	}
	return nil
}

type WorkflowExecutionProto struct {
	Uuid                 int64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectId            *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExecutionState       StateProto            `protobuf:"varint,4,opt,name=execution_state,json=executionState,proto3,enum=StateProto" json:"execution_state,omitempty"`
	Properties           map[string]string     `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StartTime            *wrappers.Int64Value  `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *wrappers.Int64Value  `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LogUri               *wrappers.StringValue `protobuf:"bytes,8,opt,name=log_uri,json=logUri,proto3" json:"log_uri,omitempty"`
	WorkflowJson         *wrappers.StringValue `protobuf:"bytes,9,opt,name=workflow_json,json=workflowJson,proto3" json:"workflow_json,omitempty"`
	Signature            *wrappers.StringValue `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WorkflowExecutionProto) Reset()         { *m = WorkflowExecutionProto{} }
func (m *WorkflowExecutionProto) String() string { return proto.CompactTextString(m) }
func (*WorkflowExecutionProto) ProtoMessage()    {}
func (*WorkflowExecutionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *WorkflowExecutionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowExecutionProto.Unmarshal(m, b)
}
func (m *WorkflowExecutionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowExecutionProto.Marshal(b, m, deterministic)
}
func (m *WorkflowExecutionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowExecutionProto.Merge(m, src)
}
func (m *WorkflowExecutionProto) XXX_Size() int {
	return xxx_messageInfo_WorkflowExecutionProto.Size(m)
}
func (m *WorkflowExecutionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowExecutionProto.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowExecutionProto proto.InternalMessageInfo

func (m *WorkflowExecutionProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *WorkflowExecutionProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkflowExecutionProto) GetProjectId() *wrappers.Int64Value {
	if m != nil {
		return m.ProjectId
	}
	return nil
}

func (m *WorkflowExecutionProto) GetExecutionState() StateProto {
	if m != nil {
		return m.ExecutionState
	}
	return StateProto_STATE_UNSPECIFIED
}

func (m *WorkflowExecutionProto) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *WorkflowExecutionProto) GetStartTime() *wrappers.Int64Value {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *WorkflowExecutionProto) GetEndTime() *wrappers.Int64Value {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *WorkflowExecutionProto) GetLogUri() *wrappers.StringValue {
	if m != nil {
		return m.LogUri
	}
	return nil
}

func (m *WorkflowExecutionProto) GetWorkflowJson() *wrappers.StringValue {
	if m != nil {
		return m.WorkflowJson
	}
	return nil
}

func (m *WorkflowExecutionProto) GetSignature() *wrappers.StringValue {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ProjectProto struct {
	Uuid                 int64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Properties           map[string]string     `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ProjectType          *wrappers.StringValue `protobuf:"bytes,4,opt,name=project_type,json=projectType,proto3" json:"project_type,omitempty"`
	Uri                  *wrappers.StringValue `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	User                 *wrappers.StringValue `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Password             *wrappers.StringValue `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProjectProto) Reset()         { *m = ProjectProto{} }
func (m *ProjectProto) String() string { return proto.CompactTextString(m) }
func (*ProjectProto) ProtoMessage()    {}
func (*ProjectProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *ProjectProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectProto.Unmarshal(m, b)
}
func (m *ProjectProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectProto.Marshal(b, m, deterministic)
}
func (m *ProjectProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectProto.Merge(m, src)
}
func (m *ProjectProto) XXX_Size() int {
	return xxx_messageInfo_ProjectProto.Size(m)
}
func (m *ProjectProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectProto proto.InternalMessageInfo

func (m *ProjectProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *ProjectProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectProto) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ProjectProto) GetProjectType() *wrappers.StringValue {
	if m != nil {
		return m.ProjectType
	}
	return nil
}

func (m *ProjectProto) GetUri() *wrappers.StringValue {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *ProjectProto) GetUser() *wrappers.StringValue {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ProjectProto) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

type ArtifactProto struct {
	Uuid                 int64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Properties           map[string]string     `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DataFormat           *wrappers.StringValue `protobuf:"bytes,4,opt,name=data_format,json=dataFormat,proto3" json:"data_format,omitempty"`
	BatchUri             *wrappers.StringValue `protobuf:"bytes,5,opt,name=batch_uri,json=batchUri,proto3" json:"batch_uri,omitempty"`
	StreamUri            *wrappers.StringValue `protobuf:"bytes,6,opt,name=stream_uri,json=streamUri,proto3" json:"stream_uri,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime           *wrappers.Int64Value  `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *wrappers.Int64Value  `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ArtifactProto) Reset()         { *m = ArtifactProto{} }
func (m *ArtifactProto) String() string { return proto.CompactTextString(m) }
func (*ArtifactProto) ProtoMessage()    {}
func (*ArtifactProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *ArtifactProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactProto.Unmarshal(m, b)
}
func (m *ArtifactProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactProto.Marshal(b, m, deterministic)
}
func (m *ArtifactProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactProto.Merge(m, src)
}
func (m *ArtifactProto) XXX_Size() int {
	return xxx_messageInfo_ArtifactProto.Size(m)
}
func (m *ArtifactProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactProto.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactProto proto.InternalMessageInfo

func (m *ArtifactProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *ArtifactProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArtifactProto) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ArtifactProto) GetDataFormat() *wrappers.StringValue {
	if m != nil {
		return m.DataFormat
	}
	return nil
}

func (m *ArtifactProto) GetBatchUri() *wrappers.StringValue {
	if m != nil {
		return m.BatchUri
	}
	return nil
}

func (m *ArtifactProto) GetStreamUri() *wrappers.StringValue {
	if m != nil {
		return m.StreamUri
	}
	return nil
}

func (m *ArtifactProto) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ArtifactProto) GetCreateTime() *wrappers.Int64Value {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *ArtifactProto) GetUpdateTime() *wrappers.Int64Value {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type RegisteredModelParam struct {
	ModelName            *wrappers.StringValue `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelType            ModelType             `protobuf:"varint,2,opt,name=model_type,json=modelType,proto3,enum=ModelType" json:"model_type,omitempty"`
	ModelDesc            *wrappers.StringValue `protobuf:"bytes,3,opt,name=model_desc,json=modelDesc,proto3" json:"model_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegisteredModelParam) Reset()         { *m = RegisteredModelParam{} }
func (m *RegisteredModelParam) String() string { return proto.CompactTextString(m) }
func (*RegisteredModelParam) ProtoMessage()    {}
func (*RegisteredModelParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *RegisteredModelParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredModelParam.Unmarshal(m, b)
}
func (m *RegisteredModelParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredModelParam.Marshal(b, m, deterministic)
}
func (m *RegisteredModelParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredModelParam.Merge(m, src)
}
func (m *RegisteredModelParam) XXX_Size() int {
	return xxx_messageInfo_RegisteredModelParam.Size(m)
}
func (m *RegisteredModelParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredModelParam.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredModelParam proto.InternalMessageInfo

func (m *RegisteredModelParam) GetModelName() *wrappers.StringValue {
	if m != nil {
		return m.ModelName
	}
	return nil
}

func (m *RegisteredModelParam) GetModelType() ModelType {
	if m != nil {
		return m.ModelType
	}
	return ModelType_NONE_TYPE
}

func (m *RegisteredModelParam) GetModelDesc() *wrappers.StringValue {
	if m != nil {
		return m.ModelDesc
	}
	return nil
}

type ModelVersionParam struct {
	ModelPath            *wrappers.StringValue `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	ModelMetric          *wrappers.StringValue `protobuf:"bytes,2,opt,name=model_metric,json=modelMetric,proto3" json:"model_metric,omitempty"`
	ModelFlavor          *wrappers.StringValue `protobuf:"bytes,3,opt,name=model_flavor,json=modelFlavor,proto3" json:"model_flavor,omitempty"`
	VersionDesc          *wrappers.StringValue `protobuf:"bytes,4,opt,name=version_desc,json=versionDesc,proto3" json:"version_desc,omitempty"`
	CurrentStage         ModelVersionStage     `protobuf:"varint,5,opt,name=current_stage,json=currentStage,proto3,enum=ModelVersionStage" json:"current_stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModelVersionParam) Reset()         { *m = ModelVersionParam{} }
func (m *ModelVersionParam) String() string { return proto.CompactTextString(m) }
func (*ModelVersionParam) ProtoMessage()    {}
func (*ModelVersionParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *ModelVersionParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelVersionParam.Unmarshal(m, b)
}
func (m *ModelVersionParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelVersionParam.Marshal(b, m, deterministic)
}
func (m *ModelVersionParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelVersionParam.Merge(m, src)
}
func (m *ModelVersionParam) XXX_Size() int {
	return xxx_messageInfo_ModelVersionParam.Size(m)
}
func (m *ModelVersionParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelVersionParam.DiscardUnknown(m)
}

var xxx_messageInfo_ModelVersionParam proto.InternalMessageInfo

func (m *ModelVersionParam) GetModelPath() *wrappers.StringValue {
	if m != nil {
		return m.ModelPath
	}
	return nil
}

func (m *ModelVersionParam) GetModelMetric() *wrappers.StringValue {
	if m != nil {
		return m.ModelMetric
	}
	return nil
}

func (m *ModelVersionParam) GetModelFlavor() *wrappers.StringValue {
	if m != nil {
		return m.ModelFlavor
	}
	return nil
}

func (m *ModelVersionParam) GetVersionDesc() *wrappers.StringValue {
	if m != nil {
		return m.VersionDesc
	}
	return nil
}

func (m *ModelVersionParam) GetCurrentStage() ModelVersionStage {
	if m != nil {
		return m.CurrentStage
	}
	return ModelVersionStage_GENERATED
}

type ModelMetaParam struct {
	ModelName            *wrappers.StringValue `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion         *wrappers.StringValue `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModelMetaParam) Reset()         { *m = ModelMetaParam{} }
func (m *ModelMetaParam) String() string { return proto.CompactTextString(m) }
func (*ModelMetaParam) ProtoMessage()    {}
func (*ModelMetaParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *ModelMetaParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelMetaParam.Unmarshal(m, b)
}
func (m *ModelMetaParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelMetaParam.Marshal(b, m, deterministic)
}
func (m *ModelMetaParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelMetaParam.Merge(m, src)
}
func (m *ModelMetaParam) XXX_Size() int {
	return xxx_messageInfo_ModelMetaParam.Size(m)
}
func (m *ModelMetaParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelMetaParam.DiscardUnknown(m)
}

var xxx_messageInfo_ModelMetaParam proto.InternalMessageInfo

func (m *ModelMetaParam) GetModelName() *wrappers.StringValue {
	if m != nil {
		return m.ModelName
	}
	return nil
}

func (m *ModelMetaParam) GetModelVersion() *wrappers.StringValue {
	if m != nil {
		return m.ModelVersion
	}
	return nil
}

type Response struct {
	ReturnCode           string   `protobuf:"bytes,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	ReturnMsg            string   `protobuf:"bytes,2,opt,name=return_msg,json=returnMsg,proto3" json:"return_msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetReturnCode() string {
	if m != nil {
		return m.ReturnCode
	}
	return ""
}

func (m *Response) GetReturnMsg() string {
	if m != nil {
		return m.ReturnMsg
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RegisteredModelMeta struct {
	ModelName            string                `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelType            ModelType             `protobuf:"varint,2,opt,name=model_type,json=modelType,proto3,enum=ModelType" json:"model_type,omitempty"`
	ModelDesc            *wrappers.StringValue `protobuf:"bytes,3,opt,name=model_desc,json=modelDesc,proto3" json:"model_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RegisteredModelMeta) Reset()         { *m = RegisteredModelMeta{} }
func (m *RegisteredModelMeta) String() string { return proto.CompactTextString(m) }
func (*RegisteredModelMeta) ProtoMessage()    {}
func (*RegisteredModelMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *RegisteredModelMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredModelMeta.Unmarshal(m, b)
}
func (m *RegisteredModelMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredModelMeta.Marshal(b, m, deterministic)
}
func (m *RegisteredModelMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredModelMeta.Merge(m, src)
}
func (m *RegisteredModelMeta) XXX_Size() int {
	return xxx_messageInfo_RegisteredModelMeta.Size(m)
}
func (m *RegisteredModelMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredModelMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredModelMeta proto.InternalMessageInfo

func (m *RegisteredModelMeta) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *RegisteredModelMeta) GetModelType() ModelType {
	if m != nil {
		return m.ModelType
	}
	return ModelType_NONE_TYPE
}

func (m *RegisteredModelMeta) GetModelDesc() *wrappers.StringValue {
	if m != nil {
		return m.ModelDesc
	}
	return nil
}

type ModelVersionMeta struct {
	ModelName            string                `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion         string                `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	ModelPath            *wrappers.StringValue `protobuf:"bytes,3,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	ModelMetric          *wrappers.StringValue `protobuf:"bytes,4,opt,name=model_metric,json=modelMetric,proto3" json:"model_metric,omitempty"`
	ModelFlavor          *wrappers.StringValue `protobuf:"bytes,5,opt,name=model_flavor,json=modelFlavor,proto3" json:"model_flavor,omitempty"`
	VersionDesc          *wrappers.StringValue `protobuf:"bytes,6,opt,name=version_desc,json=versionDesc,proto3" json:"version_desc,omitempty"`
	VersionStatus        ModelVersionStatus    `protobuf:"varint,7,opt,name=version_status,json=versionStatus,proto3,enum=ModelVersionStatus" json:"version_status,omitempty"`
	CurrentStage         ModelVersionStage     `protobuf:"varint,8,opt,name=current_stage,json=currentStage,proto3,enum=ModelVersionStage" json:"current_stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModelVersionMeta) Reset()         { *m = ModelVersionMeta{} }
func (m *ModelVersionMeta) String() string { return proto.CompactTextString(m) }
func (*ModelVersionMeta) ProtoMessage()    {}
func (*ModelVersionMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *ModelVersionMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelVersionMeta.Unmarshal(m, b)
}
func (m *ModelVersionMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelVersionMeta.Marshal(b, m, deterministic)
}
func (m *ModelVersionMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelVersionMeta.Merge(m, src)
}
func (m *ModelVersionMeta) XXX_Size() int {
	return xxx_messageInfo_ModelVersionMeta.Size(m)
}
func (m *ModelVersionMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelVersionMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ModelVersionMeta proto.InternalMessageInfo

func (m *ModelVersionMeta) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *ModelVersionMeta) GetModelVersion() string {
	if m != nil {
		return m.ModelVersion
	}
	return ""
}

func (m *ModelVersionMeta) GetModelPath() *wrappers.StringValue {
	if m != nil {
		return m.ModelPath
	}
	return nil
}

func (m *ModelVersionMeta) GetModelMetric() *wrappers.StringValue {
	if m != nil {
		return m.ModelMetric
	}
	return nil
}

func (m *ModelVersionMeta) GetModelFlavor() *wrappers.StringValue {
	if m != nil {
		return m.ModelFlavor
	}
	return nil
}

func (m *ModelVersionMeta) GetVersionDesc() *wrappers.StringValue {
	if m != nil {
		return m.VersionDesc
	}
	return nil
}

func (m *ModelVersionMeta) GetVersionStatus() ModelVersionStatus {
	if m != nil {
		return m.VersionStatus
	}
	return ModelVersionStatus_PENDING_REGISTRATION
}

func (m *ModelVersionMeta) GetCurrentStage() ModelVersionStage {
	if m != nil {
		return m.CurrentStage
	}
	return ModelVersionStage_GENERATED
}

type RegisteredModelDetail struct {
	RegisteredModel      *RegisteredModelMeta `protobuf:"bytes,1,opt,name=registered_model,json=registeredModel,proto3" json:"registered_model,omitempty"`
	ModelVersion         *ModelVersionMeta    `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RegisteredModelDetail) Reset()         { *m = RegisteredModelDetail{} }
func (m *RegisteredModelDetail) String() string { return proto.CompactTextString(m) }
func (*RegisteredModelDetail) ProtoMessage()    {}
func (*RegisteredModelDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *RegisteredModelDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredModelDetail.Unmarshal(m, b)
}
func (m *RegisteredModelDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredModelDetail.Marshal(b, m, deterministic)
}
func (m *RegisteredModelDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredModelDetail.Merge(m, src)
}
func (m *RegisteredModelDetail) XXX_Size() int {
	return xxx_messageInfo_RegisteredModelDetail.Size(m)
}
func (m *RegisteredModelDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredModelDetail.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredModelDetail proto.InternalMessageInfo

func (m *RegisteredModelDetail) GetRegisteredModel() *RegisteredModelMeta {
	if m != nil {
		return m.RegisteredModel
	}
	return nil
}

func (m *RegisteredModelDetail) GetModelVersion() *ModelVersionMeta {
	if m != nil {
		return m.ModelVersion
	}
	return nil
}

type RegisteredModelMetas struct {
	RegisteredModels     []*RegisteredModelMeta `protobuf:"bytes,1,rep,name=registered_models,json=registeredModels,proto3" json:"registered_models,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RegisteredModelMetas) Reset()         { *m = RegisteredModelMetas{} }
func (m *RegisteredModelMetas) String() string { return proto.CompactTextString(m) }
func (*RegisteredModelMetas) ProtoMessage()    {}
func (*RegisteredModelMetas) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *RegisteredModelMetas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredModelMetas.Unmarshal(m, b)
}
func (m *RegisteredModelMetas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredModelMetas.Marshal(b, m, deterministic)
}
func (m *RegisteredModelMetas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredModelMetas.Merge(m, src)
}
func (m *RegisteredModelMetas) XXX_Size() int {
	return xxx_messageInfo_RegisteredModelMetas.Size(m)
}
func (m *RegisteredModelMetas) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredModelMetas.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredModelMetas proto.InternalMessageInfo

func (m *RegisteredModelMetas) GetRegisteredModels() []*RegisteredModelMeta {
	if m != nil {
		return m.RegisteredModels
	}
	return nil
}

type MetricMetaProto struct {
	Uuid                 int64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DatasetId            *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	ModelName            *wrappers.StringValue `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion         *wrappers.StringValue `protobuf:"bytes,5,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	JobId                *wrappers.Int64Value  `protobuf:"bytes,6,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StartTime            *wrappers.Int64Value  `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *wrappers.Int64Value  `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MetricType           MetricTypeProto       `protobuf:"varint,9,opt,name=metric_type,json=metricType,proto3,enum=MetricTypeProto" json:"metric_type,omitempty"`
	Uri                  *wrappers.StringValue `protobuf:"bytes,10,opt,name=uri,proto3" json:"uri,omitempty"`
	Tags                 *wrappers.StringValue `protobuf:"bytes,11,opt,name=tags,proto3" json:"tags,omitempty"`
	MetricDescription    *wrappers.StringValue `protobuf:"bytes,12,opt,name=metric_description,json=metricDescription,proto3" json:"metric_description,omitempty"`
	Properties           map[string]string     `protobuf:"bytes,13,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MetricMetaProto) Reset()         { *m = MetricMetaProto{} }
func (m *MetricMetaProto) String() string { return proto.CompactTextString(m) }
func (*MetricMetaProto) ProtoMessage()    {}
func (*MetricMetaProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *MetricMetaProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricMetaProto.Unmarshal(m, b)
}
func (m *MetricMetaProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricMetaProto.Marshal(b, m, deterministic)
}
func (m *MetricMetaProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricMetaProto.Merge(m, src)
}
func (m *MetricMetaProto) XXX_Size() int {
	return xxx_messageInfo_MetricMetaProto.Size(m)
}
func (m *MetricMetaProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricMetaProto.DiscardUnknown(m)
}

var xxx_messageInfo_MetricMetaProto proto.InternalMessageInfo

func (m *MetricMetaProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *MetricMetaProto) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *MetricMetaProto) GetDatasetId() *wrappers.Int64Value {
	if m != nil {
		return m.DatasetId
	}
	return nil
}

func (m *MetricMetaProto) GetModelName() *wrappers.StringValue {
	if m != nil {
		return m.ModelName
	}
	return nil
}

func (m *MetricMetaProto) GetModelVersion() *wrappers.StringValue {
	if m != nil {
		return m.ModelVersion
	}
	return nil
}

func (m *MetricMetaProto) GetJobId() *wrappers.Int64Value {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *MetricMetaProto) GetStartTime() *wrappers.Int64Value {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *MetricMetaProto) GetEndTime() *wrappers.Int64Value {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *MetricMetaProto) GetMetricType() MetricTypeProto {
	if m != nil {
		return m.MetricType
	}
	return MetricTypeProto_DATASET
}

func (m *MetricMetaProto) GetUri() *wrappers.StringValue {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *MetricMetaProto) GetTags() *wrappers.StringValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MetricMetaProto) GetMetricDescription() *wrappers.StringValue {
	if m != nil {
		return m.MetricDescription
	}
	return nil
}

func (m *MetricMetaProto) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type MetricSummaryProto struct {
	Uuid                 int64                 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MetricId             *wrappers.Int64Value  `protobuf:"bytes,2,opt,name=metric_id,json=metricId,proto3" json:"metric_id,omitempty"`
	MetricKey            *wrappers.StringValue `protobuf:"bytes,3,opt,name=metric_key,json=metricKey,proto3" json:"metric_key,omitempty"`
	MetricValue          *wrappers.StringValue `protobuf:"bytes,4,opt,name=metric_value,json=metricValue,proto3" json:"metric_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MetricSummaryProto) Reset()         { *m = MetricSummaryProto{} }
func (m *MetricSummaryProto) String() string { return proto.CompactTextString(m) }
func (*MetricSummaryProto) ProtoMessage()    {}
func (*MetricSummaryProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *MetricSummaryProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricSummaryProto.Unmarshal(m, b)
}
func (m *MetricSummaryProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricSummaryProto.Marshal(b, m, deterministic)
}
func (m *MetricSummaryProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricSummaryProto.Merge(m, src)
}
func (m *MetricSummaryProto) XXX_Size() int {
	return xxx_messageInfo_MetricSummaryProto.Size(m)
}
func (m *MetricSummaryProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricSummaryProto.DiscardUnknown(m)
}

var xxx_messageInfo_MetricSummaryProto proto.InternalMessageInfo

func (m *MetricSummaryProto) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *MetricSummaryProto) GetMetricId() *wrappers.Int64Value {
	if m != nil {
		return m.MetricId
	}
	return nil
}

func (m *MetricSummaryProto) GetMetricKey() *wrappers.StringValue {
	if m != nil {
		return m.MetricKey
	}
	return nil
}

func (m *MetricSummaryProto) GetMetricValue() *wrappers.StringValue {
	if m != nil {
		return m.MetricValue
	}
	return nil
}

func init() {
	proto.RegisterEnum("ReturnCode", ReturnCode_name, ReturnCode_value)
	proto.RegisterEnum("DataTypeProto", DataTypeProto_name, DataTypeProto_value)
	proto.RegisterEnum("ExampleSupportTypeProto", ExampleSupportTypeProto_name, ExampleSupportTypeProto_value)
	proto.RegisterEnum("StateProto", StateProto_name, StateProto_value)
	proto.RegisterEnum("ExecutionMode", ExecutionMode_name, ExecutionMode_value)
	proto.RegisterEnum("ModelType", ModelType_name, ModelType_value)
	proto.RegisterEnum("ModelVersionStatus", ModelVersionStatus_name, ModelVersionStatus_value)
	proto.RegisterEnum("ModelVersionStage", ModelVersionStage_name, ModelVersionStage_value)
	proto.RegisterEnum("MetricTypeProto", MetricTypeProto_name, MetricTypeProto_value)
	proto.RegisterType((*SchemaProto)(nil), "SchemaProto")
	proto.RegisterType((*ExampleProto)(nil), "ExampleProto")
	proto.RegisterMapType((map[string]string)(nil), "ExampleProto.PropertiesEntry")
	proto.RegisterType((*ModelRelationProto)(nil), "ModelRelationProto")
	proto.RegisterType((*ModelProto)(nil), "ModelProto")
	proto.RegisterType((*ModelVersionRelationProto)(nil), "ModelVersionRelationProto")
	proto.RegisterType((*ModelVersionProto)(nil), "ModelVersionProto")
	proto.RegisterType((*JobProto)(nil), "JobProto")
	proto.RegisterMapType((map[string]string)(nil), "JobProto.PropertiesEntry")
	proto.RegisterType((*WorkflowExecutionProto)(nil), "WorkflowExecutionProto")
	proto.RegisterMapType((map[string]string)(nil), "WorkflowExecutionProto.PropertiesEntry")
	proto.RegisterType((*ProjectProto)(nil), "ProjectProto")
	proto.RegisterMapType((map[string]string)(nil), "ProjectProto.PropertiesEntry")
	proto.RegisterType((*ArtifactProto)(nil), "ArtifactProto")
	proto.RegisterMapType((map[string]string)(nil), "ArtifactProto.PropertiesEntry")
	proto.RegisterType((*RegisteredModelParam)(nil), "RegisteredModelParam")
	proto.RegisterType((*ModelVersionParam)(nil), "ModelVersionParam")
	proto.RegisterType((*ModelMetaParam)(nil), "ModelMetaParam")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*RegisteredModelMeta)(nil), "RegisteredModelMeta")
	proto.RegisterType((*ModelVersionMeta)(nil), "ModelVersionMeta")
	proto.RegisterType((*RegisteredModelDetail)(nil), "RegisteredModelDetail")
	proto.RegisterType((*RegisteredModelMetas)(nil), "RegisteredModelMetas")
	proto.RegisterType((*MetricMetaProto)(nil), "MetricMetaProto")
	proto.RegisterMapType((map[string]string)(nil), "MetricMetaProto.PropertiesEntry")
	proto.RegisterType((*MetricSummaryProto)(nil), "MetricSummaryProto")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 2340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x59, 0x4b, 0x73, 0x1b, 0xc7,
	0xf1, 0xd7, 0xe2, 0xbd, 0x8d, 0x07, 0x97, 0x43, 0x52, 0x84, 0x25, 0xdb, 0x7f, 0x16, 0xff, 0xae,
	0x0a, 0xcd, 0x54, 0xc1, 0x0e, 0x25, 0x33, 0xb2, 0x1c, 0x59, 0x59, 0x62, 0x87, 0xe4, 0x5a, 0x78,
	0x79, 0x76, 0x41, 0x8b, 0xae, 0x54, 0xb6, 0x96, 0xc0, 0x10, 0x82, 0x0c, 0x60, 0x51, 0xbb, 0x0b,
	0x49, 0x3c, 0xe4, 0x9e, 0x4b, 0xaa, 0x94, 0x7b, 0x2a, 0xf7, 0x7c, 0x84, 0xc4, 0x97, 0x54, 0xe5,
	0x98, 0x5c, 0x92, 0x43, 0x2a, 0x87, 0x1c, 0x72, 0xc8, 0x21, 0x4f, 0xe7, 0x2b, 0xa4, 0x66, 0x66,
	0x17, 0x2f, 0x53, 0xe4, 0x52, 0x50, 0x59, 0x55, 0xb9, 0xed, 0xcc, 0xf4, 0xaf, 0x67, 0xba, 0xfb,
	0xd7, 0x3d, 0x3d, 0x00, 0xe4, 0xfb, 0xd4, 0xf3, 0xec, 0x0e, 0x2d, 0x0d, 0x5d, 0xc7, 0x77, 0x6e,
	0xbc, 0xdd, 0x71, 0x9c, 0x4e, 0x8f, 0xbe, 0xc7, 0x47, 0x27, 0xa3, 0xd3, 0xf7, 0x9e, 0xba, 0xf6,
	0x70, 0x48, 0x5d, 0x4f, 0xac, 0x6f, 0x7e, 0x06, 0x59, 0xa3, 0xf5, 0x88, 0xf6, 0xed, 0x06, 0x1b,
	0xa2, 0x9b, 0x20, 0x0f, 0xec, 0x3e, 0xb5, 0x7a, 0x5d, 0xcf, 0x2f, 0x4a, 0x1b, 0xf1, 0x2d, 0x99,
	0x64, 0xd8, 0x44, 0xa5, 0xeb, 0xf9, 0xe8, 0xdb, 0x20, 0xfb, 0x67, 0xc3, 0x60, 0x31, 0xb6, 0x11,
	0xdf, 0x2a, 0xec, 0x14, 0x4a, 0x9a, 0xed, 0xdb, 0xe6, 0xd9, 0x90, 0x72, 0x3c, 0xc9, 0x30, 0x01,
	0x26, 0xbc, 0xf9, 0x55, 0x06, 0x72, 0xf8, 0x99, 0xdd, 0x1f, 0xf6, 0xc4, 0x12, 0x42, 0x90, 0x18,
	0x8d, 0xba, 0xed, 0xa2, 0xb4, 0x21, 0x6d, 0xc5, 0x09, 0xff, 0x66, 0x73, 0x4c, 0x7b, 0x31, 0xb6,
	0x21, 0x6d, 0xc9, 0x84, 0x7f, 0xa3, 0x7b, 0x00, 0x43, 0xd7, 0x19, 0x52, 0xd7, 0xef, 0x52, 0xaf,
	0x18, 0xdf, 0x88, 0x6f, 0x65, 0x77, 0xde, 0x2a, 0x4d, 0xab, 0x2a, 0x35, 0xc6, 0xeb, 0x78, 0xe0,
	0xbb, 0x67, 0x64, 0x0a, 0x80, 0x3e, 0x82, 0x9c, 0x37, 0x1a, 0x0e, 0x1d, 0xd7, 0xb7, 0xd8, 0x59,
	0x8a, 0x89, 0x0d, 0x69, 0xab, 0xb0, 0x53, 0x0c, 0x15, 0x18, 0x62, 0x6d, 0x72, 0xe2, 0xac, 0x37,
	0x99, 0x41, 0xef, 0x40, 0xca, 0xe3, 0xde, 0x28, 0x26, 0x37, 0xa4, 0xad, 0xec, 0x4e, 0xae, 0x34,
	0xe5, 0x1c, 0x12, 0xac, 0xa1, 0x0f, 0x41, 0x6e, 0xdb, 0xbe, 0x2d, 0xf4, 0xa7, 0xb8, 0xe0, 0x9b,
	0x25, 0xe1, 0xe7, 0x52, 0xe8, 0xe7, 0x92, 0xe1, 0xbb, 0xdd, 0x41, 0xe7, 0xc8, 0xee, 0x8d, 0x28,
	0xc9, 0xb4, 0x03, 0x27, 0xa1, 0x7b, 0x90, 0xe5, 0xd0, 0x53, 0xc7, 0xed, 0xdb, 0x7e, 0x31, 0x1d,
	0x01, 0x0c, 0x0c, 0xb0, 0xcf, 0xe5, 0xd9, 0xce, 0x27, 0xb6, 0xdf, 0x7a, 0x64, 0x8d, 0xdc, 0x6e,
	0x31, 0x13, 0x65, 0x67, 0x2e, 0xde, 0x74, 0xbb, 0xe8, 0x23, 0x00, 0xcf, 0x77, 0xa9, 0xdd, 0xe7,
	0x58, 0x39, 0x02, 0x56, 0x16, 0xf2, 0x0c, 0xfc, 0x31, 0x64, 0xdb, 0xd4, 0x6b, 0xb9, 0xdd, 0xa1,
	0xdf, 0x75, 0x06, 0x45, 0x88, 0x80, 0x9e, 0x06, 0xa0, 0xef, 0x41, 0xb6, 0xe5, 0x52, 0xdb, 0xa7,
	0x96, 0xdf, 0xed, 0xd3, 0x62, 0x96, 0xe3, 0x6f, 0x7e, 0x0d, 0xaf, 0x0f, 0xfc, 0xdd, 0xdb, 0x81,
	0xd5, 0x42, 0xde, 0xec, 0xf6, 0x29, 0x43, 0x8f, 0x86, 0xed, 0x31, 0x3a, 0x17, 0x01, 0x2d, 0xe4,
	0x39, 0xfa, 0x3e, 0xe4, 0x5a, 0xb6, 0x6f, 0xf7, 0x9c, 0x8e, 0xc5, 0xb9, 0x96, 0x8f, 0x72, 0xf8,
	0x00, 0x51, 0xb3, 0x67, 0x15, 0xf0, 0x88, 0x17, 0xae, 0xa0, 0x80, 0x07, 0xfd, 0x00, 0x94, 0x50,
	0x01, 0x8b, 0xe5, 0x89, 0xed, 0xd1, 0xe2, 0x52, 0x04, 0x25, 0x4b, 0x01, 0x4a, 0x0b, 0x40, 0x88,
	0xc0, 0xf5, 0x50, 0x51, 0xcb, 0x19, 0x0c, 0x68, 0x8b, 0x39, 0x97, 0xc7, 0x53, 0x89, 0xa0, 0x6e,
	0x35, 0xc0, 0x96, 0xc7, 0x50, 0x16, 0x5a, 0x0c, 0xe1, 0x36, 0xd6, 0x13, 0xea, 0x7a, 0x2c, 0xbc,
	0xcb, 0x11, 0x94, 0x15, 0x02, 0xd0, 0x91, 0xc0, 0x20, 0x15, 0xf2, 0x63, 0x27, 0xd9, 0x27, 0x3d,
	0x5a, 0x44, 0x11, 0x94, 0x84, 0x7e, 0x35, 0x19, 0xe2, 0xc6, 0x3d, 0x58, 0x9a, 0x4b, 0x6c, 0xa4,
	0x40, 0xfc, 0x0b, 0x7a, 0xc6, 0x4b, 0x86, 0x4c, 0xd8, 0x27, 0x5a, 0x85, 0xe4, 0x13, 0x86, 0x0d,
	0x4a, 0x86, 0x18, 0xdc, 0x8d, 0xdd, 0x91, 0x36, 0x9f, 0x01, 0xaa, 0x3a, 0x6d, 0xda, 0x23, 0xb4,
	0x67, 0x33, 0xe3, 0xae, 0x56, 0x75, 0xee, 0xf2, 0xaa, 0xf3, 0x98, 0xb6, 0x7c, 0xab, 0xdb, 0x2e,
	0xc6, 0x2f, 0xa7, 0x98, 0x1c, 0x88, 0xeb, 0xed, 0xcd, 0x3f, 0x49, 0x00, 0x7c, 0xeb, 0x6f, 0x6c,
	0x4b, 0xf4, 0x2e, 0x40, 0x9f, 0xed, 0x38, 0x5d, 0xe3, 0xa0, 0xc4, 0x0f, 0xc1, 0x28, 0x47, 0xe4,
	0x7e, 0xf8, 0xc9, 0x12, 0x5f, 0x88, 0xb2, 0x84, 0x0c, 0xea, 0xda, 0x25, 0x89, 0xcf, 0xe5, 0x35,
	0xea, 0xb5, 0x36, 0xff, 0x2c, 0xc1, 0x1b, 0x5c, 0x6b, 0x10, 0xe7, 0x59, 0xe7, 0xee, 0x42, 0x3a,
	0xe4, 0x8c, 0x14, 0x41, 0x6f, 0x28, 0x8c, 0x76, 0x21, 0x23, 0x8e, 0xd4, 0x6d, 0x73, 0x8f, 0x5c,
	0x62, 0x77, 0x9a, 0x0b, 0xeb, 0x6d, 0x54, 0x87, 0xb5, 0xa7, 0x8e, 0xfb, 0xc5, 0x69, 0xcf, 0x79,
	0x6a, 0xd1, 0x67, 0xb4, 0x35, 0xe2, 0xfc, 0x8f, 0xe6, 0xbc, 0x95, 0x10, 0x89, 0x43, 0xa0, 0xde,
	0xde, 0xfc, 0x49, 0x02, 0x96, 0xa7, 0xcd, 0xfb, 0xdf, 0x30, 0x6b, 0x12, 0xf2, 0xa1, 0xed, 0x3f,
	0xe2, 0xec, 0x88, 0x16, 0xf2, 0x86, 0xed, 0x3f, 0x62, 0xe5, 0x4e, 0x80, 0xfb, 0xd4, 0x77, 0xbb,
	0xd1, 0x18, 0x93, 0xe5, 0x88, 0x2a, 0x07, 0x4c, 0x14, 0x9c, 0xf6, 0xec, 0x27, 0x8e, 0x1b, 0xe9,
	0x86, 0x14, 0x0a, 0xf6, 0x39, 0x80, 0x29, 0x08, 0x5c, 0x2a, 0x38, 0x1b, 0xe5, 0x96, 0xcc, 0x06,
	0x08, 0xc6, 0x5a, 0xf4, 0x5d, 0xc8, 0xb7, 0x46, 0xae, 0x4b, 0x07, 0xbe, 0xe5, 0xf9, 0x76, 0x87,
	0xf2, 0xab, 0xb2, 0xb0, 0x83, 0x4a, 0xd3, 0xb1, 0x36, 0xd8, 0x0a, 0xc9, 0x05, 0x82, 0x7c, 0xb4,
	0xf9, 0x9b, 0x04, 0x64, 0x3e, 0x71, 0x4e, 0xae, 0x96, 0xc7, 0xaf, 0x3c, 0x7c, 0x5b, 0x20, 0x3f,
	0x76, 0x4e, 0xd8, 0xd1, 0xfd, 0x30, 0xb7, 0xb3, 0x25, 0x83, 0x8d, 0x82, 0x26, 0xeb, 0xb1, 0x73,
	0xc2, 0x87, 0xe8, 0xc3, 0x99, 0x5e, 0x29, 0xc9, 0x7b, 0xa5, 0x37, 0x4a, 0xa1, 0x05, 0x17, 0xf6,
	0x49, 0xb7, 0x20, 0xc5, 0x36, 0xe9, 0xb6, 0x23, 0xc5, 0x27, 0xf9, 0xd8, 0x39, 0xd1, 0xdb, 0xac,
	0x64, 0x79, 0xbe, 0xcd, 0x5a, 0x2b, 0x76, 0x11, 0xa7, 0x23, 0x94, 0x2c, 0x2e, 0xce, 0xef, 0xe1,
	0x5d, 0xc8, 0xd0, 0x41, 0x5b, 0x20, 0x33, 0x11, 0xb2, 0x83, 0x0e, 0xda, 0x1c, 0xf7, 0x01, 0xa4,
	0xd9, 0xad, 0x12, 0xb5, 0x6b, 0x49, 0xf5, 0x9c, 0x0e, 0xbb, 0xd7, 0xee, 0x82, 0xec, 0x75, 0x3b,
	0x03, 0xdb, 0x1f, 0xb9, 0x34, 0x52, 0xc3, 0x32, 0x11, 0x5f, 0xf4, 0x26, 0xfa, 0x6b, 0x02, 0xae,
	0x7f, 0x36, 0x1f, 0xd7, 0x6f, 0xee, 0x6e, 0xb8, 0x0d, 0x4b, 0x13, 0x1a, 0xbe, 0x90, 0x44, 0x85,
	0xb1, 0x8c, 0xa0, 0xd2, 0xc1, 0x39, 0x54, 0xfa, 0x56, 0xe9, 0x7c, 0x33, 0x2e, 0x24, 0xd6, 0x2c,
	0x47, 0x52, 0x2f, 0xcd, 0x91, 0xf4, 0xcb, 0x71, 0x24, 0x73, 0x05, 0x8e, 0xa8, 0x90, 0x1f, 0x67,
	0xee, 0x63, 0xcf, 0x19, 0x44, 0x22, 0x58, 0x2e, 0x84, 0x7c, 0xe2, 0x39, 0x83, 0xd7, 0x49, 0xb3,
	0x9f, 0xc6, 0x21, 0xd7, 0x10, 0x51, 0x7f, 0x15, 0x2f, 0xac, 0x69, 0x55, 0x17, 0x06, 0xf8, 0x3e,
	0xe4, 0x42, 0x6e, 0x8e, 0xbb, 0x8f, 0x4b, 0xcb, 0x73, 0x80, 0xe0, 0x1d, 0x49, 0x09, 0xe2, 0x2c,
	0x52, 0x51, 0x2e, 0x16, 0x26, 0x88, 0xde, 0x87, 0xc4, 0xc8, 0xa3, 0xd1, 0x2e, 0x12, 0x2e, 0x89,
	0xee, 0x40, 0x66, 0x68, 0x7b, 0xde, 0x53, 0xc7, 0x6d, 0x47, 0xba, 0x3d, 0xc6, 0xd2, 0x8b, 0xc6,
	0xe4, 0x17, 0x09, 0xc8, 0xab, 0xae, 0xdf, 0x3d, 0xb5, 0xaf, 0x1a, 0x94, 0x8f, 0xcf, 0x09, 0xca,
	0xdb, 0xa5, 0x19, 0x5d, 0x17, 0x46, 0x65, 0xee, 0x65, 0x99, 0x58, 0xe4, 0x65, 0x99, 0x5c, 0xe0,
	0x65, 0x99, 0x5a, 0xe8, 0x65, 0x99, 0x5e, 0xf0, 0x65, 0x99, 0x59, 0xe8, 0x65, 0x29, 0x5f, 0xe9,
	0x65, 0xb9, 0x28, 0x57, 0xbe, 0x94, 0x60, 0x95, 0xd0, 0x4e, 0xd7, 0xf3, 0xa9, 0x4b, 0xdb, 0xe2,
	0x01, 0x61, 0xbb, 0x76, 0x7f, 0xd2, 0xbe, 0x71, 0x92, 0x48, 0x91, 0xdb, 0x37, 0xfe, 0x5a, 0x9d,
	0x7d, 0x19, 0xc4, 0xa2, 0xbf, 0x0c, 0xe2, 0x57, 0x7b, 0x19, 0xfc, 0x2e, 0x36, 0xd7, 0x3a, 0xcf,
	0x1e, 0x9d, 0x77, 0x9e, 0xd2, 0x62, 0x9d, 0x67, 0x6c, 0xd1, 0xce, 0x33, 0xbe, 0x68, 0xe7, 0x99,
	0x58, 0xb8, 0xf3, 0x4c, 0x46, 0xec, 0x3c, 0x9f, 0x4b, 0x50, 0xa8, 0x06, 0xa6, 0xd8, 0xaf, 0x80,
	0x06, 0x2a, 0xe4, 0x05, 0x38, 0x7c, 0xc9, 0x44, 0x71, 0xa6, 0xf0, 0x5e, 0x70, 0xca, 0xcd, 0x1f,
	0x42, 0x86, 0x50, 0x6f, 0xe8, 0x0c, 0x3c, 0x8a, 0xfe, 0x0f, 0xb2, 0x2e, 0xf5, 0x47, 0xee, 0xc0,
	0x6a, 0x39, 0x6d, 0x1a, 0xf0, 0x1b, 0xc4, 0x54, 0xd9, 0x69, 0x53, 0xf4, 0x16, 0x04, 0x23, 0xab,
	0xef, 0x75, 0x02, 0xae, 0xcb, 0x62, 0xa6, 0xea, 0x75, 0x58, 0xc5, 0x63, 0xc5, 0x86, 0x47, 0x44,
	0x26, 0xfc, 0x7b, 0xf3, 0x67, 0x12, 0xac, 0xcc, 0xf1, 0x9f, 0x19, 0xcf, 0x54, 0xcd, 0xd9, 0x2d,
	0xbf, 0x0e, 0x82, 0xff, 0x36, 0x0e, 0xca, 0x74, 0xd4, 0xa2, 0x9c, 0xed, 0xff, 0xcf, 0xf3, 0xba,
	0x3c, 0xeb, 0xd7, 0xb9, 0x1c, 0x89, 0x2f, 0x96, 0x23, 0x89, 0x45, 0x73, 0x24, 0xb9, 0x68, 0x8e,
	0xa4, 0xae, 0x9a, 0x23, 0x77, 0xa1, 0x10, 0x2a, 0x60, 0xdd, 0xe9, 0xc8, 0xe3, 0x55, 0xbf, 0xb0,
	0xb3, 0x32, 0x9f, 0x24, 0xfe, 0xc8, 0x23, 0xf9, 0x27, 0xd3, 0xc3, 0x97, 0x7f, 0xd9, 0x3d, 0x97,
	0x60, 0x6d, 0x8e, 0x6c, 0x1a, 0xf5, 0xed, 0x6e, 0x0f, 0xdd, 0x07, 0xc5, 0x1d, 0x2f, 0x58, 0xdc,
	0xd2, 0x20, 0xd9, 0x56, 0x4b, 0xe7, 0xd0, 0x93, 0x2c, 0xb9, 0xb3, 0x93, 0x68, 0xf7, 0xfc, 0x54,
	0x5b, 0x2e, 0xcd, 0xb3, 0x67, 0x2e, 0xbf, 0x8e, 0xbf, 0x56, 0xfe, 0x99, 0x90, 0x87, 0x54, 0x58,
	0x9e, 0x3f, 0x90, 0xc7, 0x7f, 0x8b, 0x7f, 0xd1, 0x89, 0x94, 0xb9, 0x13, 0x79, 0x9b, 0x3f, 0x4f,
	0xc1, 0x92, 0x88, 0x37, 0x2f, 0x27, 0x2f, 0x6c, 0x44, 0xde, 0x9f, 0x6a, 0x44, 0x2e, 0xed, 0xac,
	0xc2, 0x87, 0x09, 0x4b, 0x5e, 0x8f, 0x46, 0x7e, 0x98, 0x04, 0xe2, 0xd3, 0x3f, 0x4b, 0xf0, 0x3d,
	0x13, 0x0b, 0x16, 0xb4, 0xe4, 0x55, 0x0b, 0x1a, 0xda, 0x99, 0x7b, 0xf2, 0x5e, 0x78, 0xee, 0xd7,
	0xf8, 0xe2, 0xfd, 0x0e, 0x64, 0x45, 0x76, 0x8b, 0x12, 0x27, 0x73, 0x8a, 0x2b, 0x25, 0x11, 0xd0,
	0xc9, 0x3f, 0x17, 0xd0, 0x1f, 0x4f, 0x84, 0x2d, 0x35, 0x5c, 0xa1, 0xa5, 0xf6, 0xed, 0x8e, 0x17,
	0xfc, 0x12, 0x7f, 0x49, 0xe0, 0x99, 0x24, 0x7a, 0x00, 0x28, 0x38, 0xd4, 0x74, 0xbf, 0x96, 0x8b,
	0x80, 0x5f, 0x16, 0x38, 0x6d, 0xaa, 0x6b, 0xfb, 0xfe, 0x4c, 0xb3, 0x9b, 0xe7, 0xdc, 0xde, 0x28,
	0xcd, 0x31, 0xf6, 0xa2, 0x76, 0x77, 0xd1, 0xde, 0xeb, 0x2f, 0x12, 0x20, 0xb1, 0x9d, 0x31, 0xea,
	0xf7, 0x6d, 0xf7, 0xec, 0xc5, 0x39, 0x72, 0x07, 0xe4, 0xc0, 0xf0, 0x68, 0x3f, 0xeb, 0x65, 0x84,
	0x74, 0xc0, 0x77, 0x81, 0x64, 0xe7, 0x8a, 0x56, 0xe8, 0xb9, 0xfc, 0x03, 0x7a, 0xc6, 0xeb, 0xb4,
	0x00, 0x0b, 0x13, 0xa2, 0x15, 0x7a, 0x8e, 0xe0, 0x83, 0xed, 0x5f, 0xc7, 0x01, 0xc8, 0xe4, 0x82,
	0xce, 0x42, 0xda, 0x68, 0x96, 0xcb, 0xd8, 0x30, 0x94, 0x6b, 0x08, 0x41, 0x41, 0xaf, 0x99, 0x98,
	0xd4, 0xd4, 0x8a, 0x85, 0x09, 0xa9, 0x13, 0x45, 0x42, 0x37, 0x61, 0xdd, 0xc4, 0xd5, 0x46, 0x9d,
	0xa8, 0x44, 0xaf, 0x1c, 0x5b, 0xcd, 0x9a, 0x7a, 0xa4, 0xea, 0x15, 0x75, 0xaf, 0x82, 0x95, 0x18,
	0xca, 0x41, 0x46, 0xaf, 0x07, 0xa2, 0x71, 0xb4, 0x04, 0xd9, 0x3d, 0x55, 0xb3, 0x08, 0xfe, 0xb4,
	0x89, 0x0d, 0x53, 0x49, 0xa0, 0x37, 0x61, 0x5d, 0xaf, 0x1d, 0xa9, 0x15, 0x5d, 0xb3, 0x1a, 0x2a,
	0x51, 0xab, 0xd8, 0xc4, 0xc4, 0x3a, 0x52, 0x2b, 0x4d, 0xac, 0xfc, 0x2d, 0x8d, 0xd6, 0x01, 0xe1,
	0x9a, 0xd6, 0xa8, 0xeb, 0x35, 0xd3, 0xaa, 0xd5, 0x4d, 0x6b, 0xbf, 0xde, 0xac, 0x69, 0xca, 0xdf,
	0xd3, 0xe8, 0x3a, 0x2c, 0x57, 0xd5, 0xca, 0x7e, 0x9d, 0x54, 0xf1, 0x44, 0xdb, 0x3f, 0xd2, 0x08,
	0x41, 0x3e, 0x54, 0x67, 0x98, 0xaa, 0x89, 0x95, 0x7f, 0x72, 0xd9, 0x06, 0x26, 0x55, 0xdd, 0x30,
	0xf4, 0x7a, 0xcd, 0xd2, 0x70, 0x4d, 0xc7, 0x9a, 0xf2, 0xaf, 0x34, 0x5a, 0x03, 0x65, 0x1f, 0xab,
	0x66, 0x93, 0x60, 0x4b, 0xd3, 0x0d, 0x76, 0x5c, 0x4d, 0xf9, 0x77, 0x1a, 0xdd, 0x80, 0xb5, 0x72,
	0xd3, 0x30, 0xeb, 0x55, 0x4c, 0x98, 0x29, 0x4d, 0xf3, 0xb0, 0x4e, 0xf4, 0xcf, 0xb1, 0xa6, 0x7c,
	0x95, 0x46, 0x37, 0xe1, 0x7a, 0xb0, 0x99, 0x55, 0xd1, 0xab, 0xba, 0x69, 0xe1, 0x87, 0x65, 0x8c,
	0x35, 0xac, 0x29, 0xff, 0x49, 0x33, 0x53, 0x08, 0x36, 0xea, 0x4d, 0x52, 0xc6, 0x96, 0x5a, 0x21,
	0x58, 0xd5, 0x8e, 0x2d, 0xfc, 0x50, 0x37, 0x4c, 0x43, 0xf9, 0xfd, 0xd2, 0xcc, 0xaa, 0x56, 0xc7,
	0x06, 0xb7, 0x87, 0x2f, 0x2b, 0x7f, 0x58, 0x42, 0x2b, 0x50, 0xf8, 0xb4, 0x59, 0x37, 0xd5, 0x89,
	0xc2, 0x5f, 0xae, 0x33, 0x48, 0x55, 0x7d, 0x68, 0xed, 0x55, 0xea, 0xe5, 0x07, 0x96, 0xa1, 0x7f,
	0x8e, 0x27, 0xab, 0xbf, 0x5a, 0x67, 0x67, 0x61, 0xab, 0x6c, 0x9f, 0xb9, 0xc5, 0x2f, 0xd7, 0xb7,
	0xff, 0x28, 0x41, 0x7e, 0xe6, 0xff, 0x55, 0xf4, 0x06, 0xac, 0x69, 0xaa, 0xa9, 0x5a, 0xe6, 0x71,
	0x03, 0x5b, 0xcd, 0x9a, 0xd1, 0xc0, 0x65, 0x7d, 0x9f, 0x79, 0xe2, 0x1a, 0x92, 0x21, 0xa9, 0xd7,
	0xcc, 0x5b, 0x3b, 0x8a, 0x14, 0x7c, 0xee, 0xde, 0x56, 0x62, 0x2c, 0xec, 0xfb, 0x95, 0xba, 0xca,
	0xe6, 0xe3, 0xe3, 0xc1, 0xee, 0x6d, 0x25, 0x81, 0x00, 0x52, 0x86, 0x49, 0xf4, 0xda, 0x81, 0x92,
	0x44, 0x05, 0x00, 0x8e, 0x55, 0x09, 0x51, 0x8f, 0x95, 0x54, 0x30, 0xde, 0xbd, 0x2d, 0xc6, 0x69,
	0xa4, 0x40, 0x6e, 0xbf, 0xc7, 0xb5, 0x88, 0x99, 0x0c, 0x9f, 0x11, 0xaa, 0xc4, 0x8c, 0xcc, 0x48,
	0x21, 0xf4, 0x89, 0x09, 0x60, 0xa7, 0xd8, 0x3b, 0x36, 0xb1, 0xa1, 0x64, 0x99, 0x3e, 0xfe, 0x29,
	0x96, 0x72, 0xdb, 0xcf, 0x60, 0xfd, 0x05, 0xff, 0xc7, 0xa2, 0x77, 0x60, 0x03, 0x3f, 0x54, 0xab,
	0x8d, 0x0a, 0xb6, 0x8c, 0x66, 0xa3, 0x51, 0x27, 0xe6, 0x79, 0xc6, 0x22, 0x28, 0x8c, 0xa5, 0x4c,
	0x82, 0xd5, 0xaa, 0x22, 0xa1, 0x65, 0xc8, 0x87, 0x73, 0x7b, 0xaa, 0x59, 0x3e, 0x54, 0x62, 0xec,
	0x94, 0xe3, 0xa9, 0xba, 0x79, 0xa8, 0xc4, 0xb7, 0x4f, 0x00, 0x26, 0x3f, 0x82, 0xa1, 0x35, 0x58,
	0xe6, 0x04, 0x9b, 0xd3, 0x9e, 0x81, 0x84, 0x5e, 0xd3, 0x4d, 0x45, 0x62, 0xbc, 0x37, 0x4c, 0x95,
	0x98, 0xcc, 0x4d, 0xdc, 0x99, 0xa4, 0x59, 0xab, 0xb1, 0x41, 0x9c, 0x2d, 0xed, 0xeb, 0x35, 0xdd,
	0x38, 0xc4, 0x9a, 0xf0, 0xe6, 0xbe, 0xaa, 0x33, 0xf2, 0x25, 0xb7, 0xf7, 0x21, 0x3f, 0xfe, 0xbd,
	0x8c, 0x5d, 0xc8, 0xe8, 0x6d, 0xb8, 0x81, 0x1f, 0xe2, 0x72, 0xd3, 0x64, 0xd4, 0xad, 0xd6, 0xb5,
	0x73, 0x42, 0x27, 0x4e, 0x2c, 0x05, 0x51, 0x61, 0x06, 0xc5, 0xb6, 0xcb, 0x20, 0x8f, 0xdb, 0x5a,
	0x94, 0x07, 0xb9, 0x56, 0xaf, 0x61, 0xee, 0x0c, 0xe5, 0x1a, 0xf3, 0x68, 0xf9, 0x10, 0x97, 0x1f,
	0xf0, 0xac, 0x52, 0x24, 0xee, 0x7d, 0xf5, 0x08, 0x6b, 0x5c, 0x7d, 0x45, 0x89, 0xa1, 0x14, 0xc4,
	0x0e, 0x3f, 0x50, 0xe2, 0xdb, 0x3f, 0x0a, 0xfe, 0x16, 0x9b, 0x69, 0xab, 0x50, 0x11, 0x56, 0x1b,
	0xb8, 0xa6, 0xe9, 0xb5, 0x03, 0x8b, 0xe0, 0x03, 0xdd, 0x30, 0x89, 0xca, 0x0e, 0xa7, 0x5c, 0x43,
	0xeb, 0xb0, 0x22, 0x0c, 0x99, 0x5d, 0xe0, 0xa4, 0xe2, 0xd9, 0xa0, 0xc4, 0xd1, 0x2a, 0x28, 0x21,
	0x5a, 0xc3, 0x15, 0xcc, 0x05, 0x12, 0x68, 0x05, 0x96, 0x02, 0xe4, 0x78, 0x32, 0xb9, 0xfd, 0x83,
	0xd9, 0x57, 0x22, 0x6f, 0xc6, 0x98, 0x2d, 0x07, 0xb8, 0x86, 0x89, 0x6a, 0x72, 0xf3, 0xf3, 0x20,
	0xf3, 0x64, 0xe7, 0x43, 0xee, 0x73, 0x0d, 0x37, 0x2a, 0xf5, 0x63, 0xac, 0x29, 0x31, 0x66, 0xa8,
	0x86, 0x1b, 0x04, 0x97, 0xf9, 0x2a, 0xe7, 0x30, 0x57, 0xcf, 0xbc, 0xbe, 0xfd, 0x6e, 0xd8, 0xe6,
	0x4c, 0xf8, 0xc3, 0xd6, 0x55, 0x53, 0x35, 0xb0, 0x29, 0x1c, 0x2b, 0xfc, 0x21, 0xed, 0x15, 0x41,
	0x69, 0x39, 0xfd, 0x92, 0xdd, 0x3d, 0xed, 0x39, 0x4f, 0x45, 0xf9, 0xfc, 0xb1, 0x24, 0x3d, 0x97,
	0xa4, 0x93, 0x14, 0x1f, 0xdc, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0x04, 0xa9, 0xe1,
	0x3a, 0x21, 0x00, 0x00,
}
