project_name: wide_and_deep
server_ip: localhost
server_port: 50051
notification_uri: localhost:50052
blob:
  blob_manager_class: ai_flow_plugins.blob_manager_plugins.local_blob_manager.LocalBlobManager